# Generated by Django 4.2.6 on 2023-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model_name', models.CharField(max_length=100, verbose_name='model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(max_length=100, verbose_name='storage')),
                ('graphics_card', models.CharField(max_length=100, verbose_name='graphics_card')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_life', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'laptops',
                'ordering': ['brand', 'processor', 'ram'],
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('processor', models.CharField(max_length=100, verbose_name='processor')),
                ('memory', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'pcs',
                'ordering': ['name', 'processor'],
            },
        ),
    ]
